name: "EKS Helm"
description: "Authenticates against EKS clusters using the AWS CLI and executes Helm commands. Can also be used with kubectl and SOPs commands."
inputs:
  command:
    description: "Your command (kubectl, helm, aws or sops)"
    required: true
  plugins:
    description: "The plugins that should be installed for helm"
    required: false
  repos:
    description: "The repositories that should be added"
    required: false
outputs:
  result:
    description: "Output returned by your command"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
